version: '3'

services:
  react-app:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/usr/src/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
    networks:
      - app-network
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./server:/app
    environment:
      - .env
    depends_on:
      - data-mongo
    networks:
      - app-network
    restart: unless-stopped

  data-mongo:
    container_name: data-mongo
    image: mongo:6.0.13
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
      - ./server/mongo-init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
